### ISSUE TITLE
Hi, I run the train.py and get the error:

### ISSUE THREAD

**Issue by yoooooy** [gurkirt/RetinaNet.pytorch.1.x#3]
raise SameFileError("{!r} and {!r} are the same file".format(src, dst))
shutil.SameFileError: './mnt/mercury-fast/datasets/esad/cache/FPN600x1080-0-esad-resnet50-hl4s0-bn1f1b1-bs16-SGD-lr010000-mbox/source/detectionDatasets.py' and './mnt/mercury-fast/datasets/esad/cache/FPN600x1080-0-esad-resnet50-hl4s0-bn1f1b1-bs16-SGD-lr010000-mbox//source/detectionDatasets.py' are the same file

Please send help, thank you

**Comment by yoooooy** [comment]
**Your working directories are ./mnt/mercury-fast/datasets/ ./mnt/mercury-fast/datasets/
Traceback (most recent call last):
  File "train.py", line 438, in <module>
    main()
  File "train.py", line 139, in main
    utils.copy_source(source_dir) # make a copy of source files used for training as a snapshot
  File "/media/H/zhangliuqing/baseline/SARAS-ESAD-Baseline-master/modules/utils.py", line 22, in copy_source
    shutil.copy2(os.path.join(dirpath, file), source_dir )
  File "/home/yons/anaconda3/lib/python3.8/shutil.py", line 432, in copy2
    copyfile(src, dst, follow_symlinks=follow_symlinks)
  File "/home/yons/anaconda3/lib/python3.8/shutil.py", line 241, in copyfile
    raise SameFileError("{!r} and {!r} are the same file".format(src, dst))
shutil.SameFileError: './mnt/mercury-fast/datasets/esad/cache/FPN600x1080-0-esad-resnet50-hl4s0-bn1f1b1-bs16-SGD-lr010000-mbox/source/detectionDatasets.py' and './mnt/mercury-fast/datasets/esad/cache/FPN600x1080-0-esad-resnet50-hl4s0-bn1f1b1-bs16-SGD-lr010000-mbox//source/detectionDatasets.py' are the same file**

**Comment by gurkirt** [comment]
It seems like you haven't change the directories.  "./mnt/mercury-fast/datasets" is only valid on my machine you need to specify data_root and save_root in arguments based on your directory structure.
