### ISSUE TITLE
print_lr() takes 1 positional argument but 5 were given

### ISSUE THREAD

**Issue by sajjadafridi** [gurkirt/RetinaNet.pytorch.1.x#4]
Hi,

I am facing this error for the last 2 days, i tried all the possible solution but no way. The same error can be found when running this repo https://github.com/Viveksbawa/SARAS-ESAD-Baseline.
Can you please help me in this regard.
For your reference i attached an image for the error.

Thanks in adv

![image](https://user-images.githubusercontent.com/31101975/117004372-6d943700-acff-11eb-986e-cde26740cfde.png)

**Comment by gurkirt** [comment]
WarmupMultiStepLR is inherited from torch.optim.lr_scheduler._LRScheduler print function is inherited from there as well. Either implement print_lr function under  WarmupMultiStepLR calls in solver.py or change the call which matches to torch.optim.lr_scheduler._LRScheduler.print_lr(kw***)  call.  torch.optim.lr_scheduler._LRScheduler.print_lr(kw***) changes with PyTorch version. So, I would suggest adding print function under WarmupMultiStepLR class.

**Comment by gurkirt** [comment]
Sorry, the wrong answer there.

Just remove print_lr() function from WarmupMultiStepLR class in solver.py.
